//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string CodeStaff { get; set; }
        public string Position { get; set; }
        public string FullName { get; set; }
        public string Log { get; set; }
        public string Password { get; set; }
        public string LastEnter { get; set; }
        public string TypeEnter { get; set; }
    }
}
